### ISSUE TITLE
getJobs Exception

### ISSUE THREAD

**Issue by 0312birdzhang** [SUSE/saltstack-netapi-client-java#81] opened 2015-07-01 11:36 UTC
My code is:
```java
URI uri = URI.create("http://127.0.0.1:8000");
SaltStackClient client = new SaltStackClient(uri);
 try {
    Token token = client.login("username", "passoword", PAM);
    ScheduledJob job = client.startCommand("*", "cmd.run", param, kwargs);
    System.out.println(job.getMinions());
    Map<String, Job> jobs = client.getJobs(); 
    ......
```
Excetion happened when executed to  <code>Map<String, Job> jobs = client.getJobs(); </code>
I can get minions and run commands,but getjobs not work.
The exception message:
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 125 path $.return[0]..Target-type
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.suse.saltstack.netapi.parser.JsonParser.parse(JsonParser.java:91)
	at com.suse.saltstack.netapi.client.impl.HttpClientConnection.executeRequest(HttpClientConnection.java:193)
	at com.suse.saltstack.netapi.client.impl.HttpClientConnection.request(HttpClientConnection.java:85)
	at com.suse.saltstack.netapi.client.impl.HttpClientConnection.getResult(HttpClientConnection.java:73)
	at com.suse.saltstack.netapi.client.SaltStackClient.getJobs(SaltStackClient.java:375)
	at com.cmdb.cron.CheckSaltClient.main(CheckSaltClient.java:63)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 125 path $.return[0]..Target-type
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:837)
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:358)
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:346)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	... 16 more
```

**Comment by hustodemon** [comment] 2015-07-01 12:56
Hello! This could be a bug. 

Could tell us what are the values of `params` and `kwargs` variables you are passing to `client.startCommand(...)`?

Also I think it would be interesting if you could paste the output of the GET request on the `/jobs` endpoint. You can do it like this:

1. Firstly log in: `curl -sSk http://YOUR_PROXY:PORT/login -c cookies.txt -H 'Accept: application/x-yaml' -d username=SALT_USERNAME -d password=SALT_PASSWORD -d eauth=auto`
2. Then run the request: `curl -b cookies.txt http://localhost:8080/jobs` to see the result

Thanks!

**Comment by 0312birdzhang** [comment] 2015-07-01 13:06
```
List<String> params = new ArrayList<>();
        params.add("uname");

        Map<String, String> kwargs = new LinkedHashMap<String, String>() {
            {
            }
        };
```

I use  
```shell
curl -k https://127.0.0.1:8000/jobs/ \
     -H "Accept: application/x-yaml" \
     -H "X-Auth-Token: 8e211da5d6bbb51fbffe6468a3ca0c6a24b3e535"
```
can get the jobs

**Comment by whiteinge** [comment] 2015-07-01 19:40
@0312birdzhang What version of Salt are you running?

There is a regression in the current develop branch (saltstack/salt#25107) that will be fixed. 2015.5 is unaffected.

**Comment by 0312birdzhang** [comment] 2015-07-02 01:36
@whiteinge salt 2015.5.1 (Lithium)

**Comment by whiteinge** [comment] 2015-07-02 01:41
Ok. Then you are not affected by the bug I referenced and this is
something else. I'll defer to @hustodemon. Sorry for the noise. :)

It may be helpful to see a sample of the data structure that you get
back from salt-api. If you are using an external job cache or a master
job cache some returner modules don't adhere to the correct return
structure (and should be fixed).

**Comment by hustodemon** [comment] 2015-07-02 07:44
@0312birdzhang :
I just tested on `salt-master 2014.7.1` with
```java
List<String> params = new ArrayList<>();
params.add("uname");
Map<String, String> kwargs = new LinkedHashMap<String, String>() {{ }};

ScheduledJob job = client.startCommand("*", "test.ping", params, kwargs);
Map<String, Job> jobs = client.getJobs();
```
and it works fine for me.

In https://github.com/SUSE/saltstack-netapi-client-java/issues/81#issuecomment-117658630, you said you can get the jobs. I'd be interested in the **JSON** output of this `curl` command. It'd help a lot with analyzing the issue.

@whiteinge Hi and thanks for the comments! I think there is some difference in the `arg`/`kwarg` output between the salt versions (2015.5.1 and 2014.7.1) which causes this trouble.

**Comment by whiteinge** [comment] 2015-07-02 07:51
Yikes. Yeah, if the JSON output is different between 2014.7 and 2015.5 that is definitely a regression and a bug.

**Comment by 0312birdzhang** [comment] 2015-07-02 08:56
@hustodemon  The jobs i can get is from curl command,and the result is:
```
return:
- '20150701170407205190':
    Arguments: []
    Function: cmd.run
    StartTime: 2015, Jul 01 17:04:07.205190
    Target: unknown-target
    Target-type: []
    User: root
  '20150701170407243621':
    Arguments: []
    Function: runner.jobs.lookup_jid
    StartTime: 2015, Jul 01 17:04:07.243621
    Target: PC3GD000952_master
    Target-type: []
    User: zhangdebo
```

**Comment by hustodemon** [comment] 2015-07-02 14:12
@whiteinge Oh, so the API between those versions should be consistent? If it's really so, I'll go through the github issues and will possibly create an issue in salt.

@0312birdzhang Cool, thanks for the output! But I'd like to ask you for the **JSON** output. You mentioned you get your output by running 
```bash
curl -k https://127.0.0.1:8000/jobs/ \
     -H "Accept: application/x-yaml" \
     -H "X-Auth-Token: 8e211da5d6bbb51fbffe6468a3ca0c6a24b3e535"
```
This produces **YAML**. Could you run the `curl` again but with 
```bash
-H "Accept: application/json"
```
? That means:
```bash
curl -k https://127.0.0.1:8000/jobs/ \
     -H "Accept: application/json" \
     -H "X-Auth-Token: 8e211da5d6bbb51fbffe6468a3ca0c6a24b3e535"
```
This should produce **JSON** output. If this output is valid, we could use it for our unit tests, which would be nice.

Thanks guys!

**Comment by whiteinge** [comment] 2015-07-02 15:26
@hustodemon it should absolutely be consistent between versions.

In addition I would recommend calling the runner directly instead of going through the `/jobs` wrapper URL. It will provide more raw output:

```
curl -k https://127.0.0.1:8000 \
     -H "Accept: application/json" \
     -H "X-Auth-Token: 8e211da5d6bbb51fbffe6468a3ca0c6a24b3e535" \
    -d client=runner \
    -d fun=jobs.list_jobs

curl -k https://127.0.0.1:8000 \
     -H "Accept: application/json" \
     -H "X-Auth-Token: 8e211da5d6bbb51fbffe6468a3ca0c6a24b3e535" \
    -d client=runner \
    -d fun=jobs.lookup_jid
    -d jid=<jid_here>
```

**Comment by 0312birdzhang** [comment] 2015-07-03 01:31
@hustodemon See here:
https://gist.github.com/0312birdzhang/308bed75aeb3d33c573d#file-jobs-json
Sorry for the late reply

**Comment by hustodemon** [comment] 2015-07-06 09:12
Thanks guys.

It seems that the problem is in the `Target-type` field. Our parser treats this field as a string, but according to saltstack source code this field can be also `[]` in some cases. This is not nice of the API but we should be able to parse this anyway.

@whiteinge I wonder if there is any possibility to get a comprehensive view of the Salt API? When I write a new parser, I usually `grep` the Salt sources for the things I need :smile:. I'm not sure if this is a best way to do it.

**Comment by whiteinge** [comment] 2015-07-07 03:08
That's odd. I can reproduce that locally with job cache results from runner functions too. I can't think of an instance where a target type is anything other than a string. I filed a ticket on the Salt repo and will follow-up on it in-office tomorrow.

@hustodemon you're right to want a documented view of the Salt API. I'd personally like to see a few things in Salt validated against a schema or at least have regression test so we can avoid unintentional API changes. Although Salt uses data structures everywhere it's not always obvious when changing a CLI tool that it will affect the Python API as well. We don't have anything that definite quite yet. That said, this and a few related topics, have been a recurring topic of discussion this year. We're starting to do some work with jsonschema internally so I'm optimistic we'll get there but it's still a ways off.

**Comment by whiteinge** [comment] 2015-07-07 20:44
@0312birdzhang are you using a returner or the `external_job_cache` or `master_job_cache`? If so, which one are you using?

**Comment by 0312birdzhang** [comment] 2015-07-08 05:00
@whiteinge  master and minion are both on my localhost,so  i think it's <code>master_job_cache</code>
:laughing:  I'm a newer of salt

**Comment by whiteinge** [comment] 2015-07-08 23:31
Thanks for the reply. That's starting to make more sense. I think whatever returner module your `master_job_cache` setting points to has not be written according to standards. We need to vet all of them. What is that setting set to in your master config? We can start with fixing that one.

**Comment by 0312birdzhang** [comment] 2015-07-09 01:29
@whiteinge 
```
birdzhang@PC3GD000952$ cat /etc/salt/master 
rest_cherrypy:
 host: 127.0.0.1
 port: 8000
 debug: true
 disable_ssl: True
 
external_auth:
   pam:
     admin:
     - .*
     - '@runner'
     - '@wheel'
minion_data_cache: False
```

**Comment by hustodemon** [comment] 2015-07-09 08:40
Ok guys, so it's indeed a bug in salt. I'm referencing the related question saltstack/salt#25199.

I suggest leaving this issue open for tracking until we release a new version. If the bug is not fixed in salt by then and we decide to handle it on our side, I will create a patch for that. But I hope this won't be needed - I'm definitely against polluting the code with workarounds.

Thanks

**Comment by 0312birdzhang** [comment] 2015-07-09 09:14
Thank you guys :smile:

**Comment by hustodemon** [comment] 2015-07-10 07:40
After more thinking I believe we should close this issue and move possible further discussion to the salt project page (as we are dealing with a salt bug here).

@0312birdzhang If you desperately need to use this library with your version of salt, you can try to apply a simple workaround I wrote [in this branch](https://github.com/SUSE/saltstack-netapi-client-java/tree/targettype_workaround).

**Closed by hustodemon** 2015-07-10 07:40 UTC
Labels: bug

**Comment by 0312birdzhang** [comment] 2015-07-10 08:56
@hustodemon Thanks very much !

**Comment by whiteinge** [comment] 2016-03-01 22:39
This may have been resolved in Salt. See [this comment](https://github.com/saltstack/salt/issues/25199#issuecomment-190937947).
