### ISSUE TITLE
Event processing is not completely shutdown

### ISSUE THREAD

**Issue by renner** [SUSE/saltstack-netapi-client-java#63] opened 2015-05-12 12:28 UTC
Not sure if this is actually a problem, it might be even expected: Running the minimal example below does apparently not shutdown the event processing thread completely, even though `shutdownNow()` is used in [`close()`] (https://github.com/SUSE/saltstack-netapi-client-java/blob/master/src/main/java/com/suse/saltstack/netapi/event/EventStream.java#L158). Instead the process keeps on running until terminated manually:

    try (EventStream stream = client.events()) {
        stream.addEventListener(new EventListener() {
            @Override
            public void notify(String data) {
            }
            @Override
            public void eventStreamClosed() {
            }
        });
    }

**Comment by lucidd** [comment] 2015-05-20 22:04
I guess it is a problem. I noticed while experimenting on travis for #68 that a test run failed because `JerseyServerSentEventsTest` got stuck and travis terminated the run.
You can find the test run [here](https://travis-ci.org/lucidd/saltstack-netapi-client-java/jobs/63388794) (scroll to the end of the logs to see the error message).
Upon running `mvn test` multiple times locally i could reproduce the same behavior.
So until we fix this we should keep in mind that travis can randomly fail on PRs for no good reason.

**Comment by lucidd** [comment] 2015-05-31 11:15
As far as i can tell the problem is the `EventInput.read()` call that blocks the thread. I thought that closing the `EventInput` would take care of that and interrupt it but it seems that `EventInput.close()` does nothing. It passes the close to the underling `InputStream` which is a special implementation by them called `UnClosableInputStream` and only logs that close has been called but nothing else.

**Comment by winglet** [comment] 2015-06-08 09:46
Hi all. 
@lucidd  I've been digging around this for a few days now as I'm having some issues passing the tests in my local env. I might have set up something wrong or my issues might be related to your travis fails.
Specifically I'm failing 3 tests (2 errors and 1 fail) in `JerseyServerSentEventsTest` - namely `testEventMessageContent()`, `testEventProcessingStateStopped()` and `shouldFireNotifyMultipleTimes()`. Reason for that is that "server reply" `TEXT_EVENT_STREAM_RESPONSE` comes as one chunk (i.e. one event) instead of 6 (as in \n\n delimited events_stream.txt).

@renner I can see the thread hanging on even after example has been run but I'm actually unable to get events with the example itself.  Instead I used a threaded listener :

```
package com.suse.saltstack.netapi.client;

import com.suse.saltstack.netapi.event.EventListener;

class SaltEventListenerClient extends Thread implements EventListener {

   private boolean finished = false;
   
    @Override
    public void notify(String eventasstring) { 
    	System.out.println(eventasstring);
    }
    @Override
    public void eventStreamClosed() { 
    	finished = true;
    }
    @Override
    public void run() {
    	while (!finished) {
    	} 
    	return;
    }	
}
```
That one stays on and is listening (and printing events) but all the same the thread does not die out after it gets finished. I think it should be killed if underlying sockets were closed but I couldn't find any way to get access them.

Cheers

**Comment by renner** [comment] 2015-06-08 10:03
Hey @winglet, thanks for your efforts investigating this issue! Please note that my code example should just represent a minimal block of code to reproduce the bug, it surely will not show any events and was never supposed to do that.

**Comment by lucidd** [comment] 2015-06-08 11:49
@winglet Thanks for reporting. It seems that you have different problems then what i experienced so far. All the tests pass fine for me it is just that in rare cases like (1 / 100 runs)  one test hangs. That's also what happened on travis it got stuck and the 10 minute travis timeout killed the test. Can you give us a little more information about  your test environment?

**Comment by winglet** [comment] 2015-06-08 12:07
@renner Yup, makes sense. I was lazy enough to just copy/paste/run. Sorry about that :-)  
@lucidd Nothing too special or customized AFAIK. Eclipse Luna Service Release 2 (4.4.2), jre 1.8.0_45, gson 2.3.1, JUnit  4.12 (jersey attached as an image: 
![jersey](https://cloud.githubusercontent.com/assets/12730010/8034347/aa44974c-0dde-11e5-8c88-5ee6c243a96d.jpg)
Anything else that might be relevant?

**Comment by lucidd** [comment] 2015-06-08 15:32
@winglet did the tests only fail in your eclipse setup or do they also fail when you run `mvn test`?

**Comment by winglet** [comment] 2015-06-08 16:31
Same 2 errors and 1 fail when `mvn test` https://gist.github.com/winglet/5f655034c153c9f07d0a#file-gistfile1-txt

**Comment by lucidd** [comment] 2015-06-08 19:38
@winglet the `IndexOutOfBoundsException` definitely looks like a different bug. Judging from the screenshot it looks like you are on windows so it might be related to different newline characters. It might be that your git client is configured to convert newlines on checkout and commit. Can you post the output of `git config --list`.

**Comment by winglet** [comment] 2015-06-08 22:07
Spot on ! 
I'm on windows indeed and I'm using egit on eclipse. 
Changed egit config to: 
```
[core]
	symlinks = false
	repositoryformatversion = 0
	filemode = false
	logallrefupdates = true
	autocrlf = true
[remote "origin"]
	url = https://github.com/SUSE/saltstack-netapi-client-java.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```
change being the addition of `autocrlf = true` and I re-checked out events_stream.txt
All tests pass now!
Sorry for the confusion.

On the initial issue (event thread staying alive) I think too that the issue lies in the implementation of `close()` in jersey's `org.glassfish.jersey.client.ChunkedInput`
```
    @Override
    public void close() {
        if (closed.compareAndSet(false, true)) {
            if (inputStream != null) {
                try {
                    inputStream.close();
                } catch (final IOException e) {
                    LOGGER.log(Level.FINE, LocalizationMessages.CHUNKED_INPUT_STREAM_CLOSING_ERROR(), e);
                }
            }
        }
    }
```
according to http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#close%28%29 : 
> The close method of InputStream does nothing. 
meaning (if I get this right) that one should get the accurate implementation of InputStream first and then call close() on it, e.g. see discussion here http://stackoverflow.com/questions/9547843/do-i-need-to-close-an-inputstream-in-java

**Comment by lucidd** [comment] 2015-06-09 08:32
@winglet No problem. Glad to here that it works now. 

As for the the problem with closing. When i was debugging that part of the code the the `InputStream`  used by `org.glassfish.jersey.client.ChunkedInput` was of type `UnclosableInputStream` and the close method of that is:

```java
public void close() throws IOException {
    if(ReaderInterceptorExecutor.LOGGER.isLoggable(Level.FINE)) {
        ReaderInterceptorExecutor.LOGGER.log(Level.FINE, LocalizationMessages.MBR_TRYING_TO_CLOSE_STREAM(this.reader.getClass()));
    }
}
```

So calling close on the `ChunkedInput` does nothing because its just calling close on the `UnclosableInputStream`. So it seems that we cant get it to pass the close down to the actual socket which should cancel all the blocking operations.

PS: if you put the language name after the ``` then you get syntax highlighting :smile:

**Comment by lucidd** [comment] 2015-08-13 10:01
This issue should be fixed since we switched to websockets for events.

**Closed by lucidd** 2015-08-13 10:01 UTC
Labels: bug
